name: ice_breaker
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - aiohttp
  - attrs
  - babel
  - beautifulsoup4
  - black
  - cryptography
  - flask
  - jinja2
  - langchain
  - numpy
  - pandas
  - requests
  - sqlalchemy
  - wheel
  - linkedin-api
  - selenium
  - webdriver-manager
  - chromedriver-binary
  - beautifulsoup4
  - snowflake-snowpark-python
  - rdflib>=6.0.0
  - pyshacl>=0.20.0
  - owlready2
  - graphviz
  - openjdk=17
  - plantuml
  - rdflib
