name: ice_breaker
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - rdflib>=6.0.0
  - snowflake-snowpark-python>=1.5.0
  - dataclasses>=0.8
  - typing-extensions>=4.0.0
  - sqlparse>=0.4.0
  - pandas>=1.5.0
